Algoritmo "MeuPrimeiroPrograma"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   :
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a) evanilson Carvalho sousa
// Data atual  : 02/02/2021
Var
// Seção de Declarações das variáveis 
        nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       nota <- 100
       escreva("resultado:", nota)

Fimalgoritmo